apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  type: NodePort
  ports:
    - protocol: TCP
      port: 4499    # Port on which the service will be exposed on the nodes
      targetPort: 4499  # Port on which your application is listening inside the container
      nodePort: 30000   # The port on which your service will be accessible from outside the cluster

